### ISSUE TITLE
Get rid of Boost unit_test_framework

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#1]
Consider substituting Boost thread with Gtest

**Comment by elshize** [comment]
Can we divide this task into these two?

1. Add dependency for the new testing framework. (So we can write new tests already in it)
2. Rewrite existing tests and get rid of Boost.Test (Later)

Also, I highly recommend using [Catch2](https://github.com/catchorg/Catch2), which is more intuitive and modern than GTest, and is being continuously developed.

**Comment by elshize** [comment]
Note that Catch2 is header-only, so it is easy to add it to the project + it supports CMake, so you can easily add individual tests to run with `ctest`.

**Comment by amallia** [comment]
Agreed. Created the two issues we need to complete the milestone:

- https://github.com/pisa-engine/pisa/issues/28
- https://github.com/pisa-engine/pisa/issues/29
