### ISSUE TITLE
Upgrade CLI11 to 1.8 once released

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#118]
**Additional context**

In `master`, they added something we should definitely use, as it's clean and useful:
https://github.com/CLIUtils/CLI11/pull/222

Essentially, you can add a set of available values, e.g., 
```
stemmer_option->check(CLI::IsMember{"porter2", "krovetz", "none"});
```
This feature is tagged for version `1.8`.

**Comment by amallia** [comment]
Solved
