### ISSUE TITLE
Store properties and statistics of an index

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#125]
I was thinking that maybe we should use an additional file, say, JSON format, to store some additional information about an index, such as document/term count, no. postings, etc.

**Additional context**

For one, this is good to have. But I also have an inspirational example: When parsing a collection, we produce a forward index in `binary_collection` without any information about number of terms. But later on, inverting can be significantly simplified if term count is known, so we pass it in command line. This is (a) annoying, (b) error prone, and (c) makes it more difficult (or less efficient) if we'd like to automate inverting all shards at a time (either from the program or a script). It would be nice if we had a file we can read those stats from.

**Backwards compatibility**

I'd say we can make it a mandatory file for an inverted index, and only an optional for inverted index for now. But even if we don't use it from code compressing index, we can use those stats.

**Comment by amallia** [comment]
Duplicate: https://github.com/pisa-engine/pisa/issues/143
