### ISSUE TITLE
Gov2 parsing

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#126]
**Summary**
We need to be able to parse GOV2 collection.

**Additional context**

We need to be able to use another format, say, `trec` in this function https://github.com/pisa-engine/pisa/blob/master/src/parse_collection.cpp#L15

**Format**
As far as I can tell (but needs to be verified) the record format is:
```
<DOC>
<DOCNO>TRECID</DOCNO>
<DOCHDR>...</DOCHDR>
HTML CONTENT
</DOC>
```
So it's simple enough, we might be able to get by without any XML parsing. We have to:
1. Extract TRECID as title
2. Extract URL from inside of `DOCHDR` (I think it's always first line)
3. And HTML CONTENT as content.

**Comment by JMMackenzie** [comment]
Just for reference, this is `trecweb` format, a type of SGML. Note that there also exists `trectext` so you might want to be a little careful on the flag name for future expansion issues.

Indri has some references on the types, see [here](https://sourceforge.net/p/lemur/wiki/Indexer%20File%20Formats/).

**Comment by elshize** [comment]
@JMMackenzie Thanks, I'll take this into account!
