### ISSUE TITLE
Slowness in query algorithms due to new design

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#130]
**Describe the bug**
I have compared the new algorithms, in particular MaxScore, to the previous design and I have noticed that previously we used `norm_len` relatively to a document multiple times, by loading it only once and storing it into a temporary variable. 

This cannot be done anymore with the current design. This probably impacts performance a bit. Any ideas?

Previously:
https://github.com/pisa-engine/pisa/blob/3bfbdec0da399dcb278d61d496ae348b999644fe/include/query/algorithm/maxscore_query.hpp#L65-L88

While now:
https://github.com/pisa-engine/pisa/blob/43665f94a17125b6c566c850a36fe11c235d10a0/include/pisa/query/algorithm/maxscore_query.hpp#L54

**Comment by JMMackenzie** [comment]
You're not recomputing the normalised length for each scorer call, right? It's just getting it out of the appropriate `wand_data` element?  

How much slower are you talking here? I wouldn't expect this to make a huge difference unless it was inducing a bunch of cache misses or something but that seems extremely unlikely.

Sorry for the short response as I'm currently mobile, but I can investigate further tomorrow.

**Comment by amallia** [comment]
> You're not recomputing the normalised length for each scorer call, right? It's just getting it out of the appropriate wand_data element?

Yes correct!

> How much slower are you talking here? I wouldn't expect this to make a huge difference unless it was inducing a bunch of cache misses or something but that seems extremely unlikely.

The slowness is noticeable only with maxscore family and it is 10% (+0.2 ms/query in avg).  

Thanks for the prompt response actually! Let's collect ideas and see if we can find anything interesting here.

**Comment by elshize** [comment]
It sounds unlikely that this would be the problem. Wouldn't it also affect WAND? But it should be easy enough to modify maxscore to precompute that just to test performance. You still have all the data available to score using the old method, don't you?

**Comment by JMMackenzie** [comment]
I agree with @elshize that it would also impact wand, though I think maxscore might compute more individual scores than wand does just based on differences in the execution paths (I'm not 100% sure this is true but I do recall looking at this a few years back). In that case, it could cause a more noticeable difference for maxscore.

Another simple idea is to just profile the runs and ensure you're actually scoring the same number of documents for both versions - I don't think anything is wrong with the algorithm (at least based on my 2 minute appraisal) but it might help track down the issue.

**Comment by amallia** [comment]
> I agree with @elshize that it would also impact wand, though I think maxscore might compute more individual scores than wand does just based on differences in the execution paths (I'm not 100% sure this is true but I do recall looking at this a few years back). In that case, it could cause a more noticeable difference for maxscore.

Yes MaxScore does much more scoring than WAND. Quite surprisingly WAND is slightly faster than before now though.

> Another simple idea is to just profile the runs and ensure you're actually scoring the same number of documents for both versions - I don't think anything is wrong with the algorithm (at least based on my 2 minute appraisal) but it might help track down the issue.

The algorithm itself is unchanged. I will ensure it produces the same output though.

**Comment by JMMackenzie** [comment]
You could pass `cur_doc` into the scoring function to avoid accessing the `ordered_cursors[I]->docs_enum` to grab the doc identifier, but I doubt it saves much since you have to access that structure to get the frequency anyway.

**Comment by amallia** [comment]
This is the commit that introduced the slowness: https://github.com/pisa-engine/pisa/pull/108/commits/4912c3df61fd2cebb50df2c906e324c674877c6c

The algorithm is identical. And scoring was still done in the exact same way as before.
The only difference I can see is this one: https://github.com/pisa-engine/pisa/pull/108/commits/4912c3df61fd2cebb50df2c906e324c674877c6c#diff-7cc7c1f839b3901ff338716a6beee97bR173

**Comment by JMMackenzie** [comment]
I did some tests with [4912cd](https://github.com/pisa-engine/pisa/commit/4912c3df61fd2cebb50df2c906e324c674877c6c), [head](https://github.com/pisa-engine/pisa/commit/fc436fd3017d18ada9edf792f96c4f65d7ac6148), and [e5615b](https://github.com/pisa-engine/pisa/commit/e5615b18627dcd5f257fa09375bcb6914cd72540) which is a bit older again.

I ran some queries across `gov2` and found some variance in the runtime as expected. See below. I am using `opt` PEF and I report _k_ = 10 and _k_ = 1000. I think the query log I used was the standard 150 topics for Gov2 on TREC (701-850). Perhaps I should do more rigorous testing.

Current head
```
{"type": "opt", "query": "maxscore", "avg": 14934.2, "q50": 7872, "q90": 39024, "q95": 57227}
{"type": "opt", "query": "maxscore", "avg": 40900.5, "q50": 33891, "q90": 81064, "q95": 111043}
```

Current head using block_max cursors instead
```
{"type": "opt", "query": "maxscore", "avg": 14769.1, "q50": 7820, "q90": 39053, "q95": 55117}
{"type": "opt", "query": "maxscore", "avg": 41635.9, "q50": 34164, "q90": 83221, "q95": 112566}
```

HEAD is now at e5615b1... Tool for evaluating queries (#100)
```
{"type": "opt", "query": "maxscore", "avg": 15071.9, "q50": 7732, "q90": 41120, "q95": 57416}
{"type": "opt", "query": "maxscore", "avg": 39598.5, "q50": 32820, "q90": 79878, "q95": 102769}
```

Back to current head, but creates the vector of cursors inline in queries.cpp instead of calling `make_max_scored_cursors`
```
{"type": "opt", "query": "maxscore", "avg": 14885.1, "q50": 7798, "q90": 39111, "q95": 55678}
{"type": "opt", "query": "maxscore", "avg": 41516, "q50": 34543, "q90": 82076, "q95": 108937}
```

**Comment by amallia** [comment]
Closing this one since the slowness is negligible and it might be just some fluctuation.
