### ISSUE TITLE
Add parallel query processing 

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#151]
Add a CLI argument to specify the number of threads to use to perform query processing.
The default should be `1`, but if a number higher than one is specified qp should be parallelized on a per query base.

**Comment by JMMackenzie** [comment]
Did we have a particular framework for threading in mind? I'm not entirely up-to-date with how we are approaching all of the design details.

**Comment by amallia** [comment]
`TBB` since it is already a dependency. 
This should be a pretty simple task, all we need is to do a parallel-for.
