### ISSUE TITLE
Doc: Missing self. in the python example code

### ISSUE THREAD

**Issue by binshengliu** [pisa-engine/pisa#196]
**Describe the bug**
Missing `self.` in the python example code. [Reading the collection using Python](https://pisa.readthedocs.io/en/latest/index_format.html#reading-the-collection-using-python)

**To Reproduce**
1. Run the python example code at [Reading the collection using Python](https://pisa.readthedocs.io/en/latest/index_format.html#reading-the-collection-using-python)

**Error message**
```
<ipython-input-1-34a20f8d2735> in __iter__(self)
      8     def __iter__(self):
      9         i = 2
---> 10         while i < len(docs):
     11             size = self.docs[i]
     12             yield (self.docs[i+1:size+i+1], self.freqs[i+1:size+i+1])

NameError: name 'docs' is not defined
```

**Expected behavior**
NA

**Environment info**
Operating System: NA
Compiler name: NA
Compiler version: NA

**Comment by amallia** [comment]
Thank you @binshengliu.
I opened #197 to fix this. 

In the new version I am using `mmap` to read the collections, s.t. also big collections can be read with limited amount of RAM.
