### ISSUE TITLE
Have an official chat

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#198]
**Describe the solution you'd like**
Although most of us are already in contact, either via email or slack, I feel we should have an official channel. It could be on Slack or any other tool, I don't mind.

I would be fine with a channel on the SIGIR workgroup too.

**Comment by elshize** [comment]
I'm fine with opening another slack group/workspace, whatever that's called.

**Comment by amallia** [comment]
[Slack](https://pisa-engine.slack.com) created
