### ISSUE TITLE
Bisection document lexicon reordering ends in runtime_error

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#205]
If you do the bisection and pass in a doclex file to be reordered, the call to `auto documents = Payload_Vector<>::from(*documents_filename);` results in a runtime_error.

I think the bug is inside the `Payload_Vector<>::from()` call. I have pushed a PR for a workaround that mitigates this by avoiding this call.

**Comment by elshize** [comment]
I'll take a look at sometime. In the meantime, let me know if despite the workaround there are still problem, or there are problems in any other part of the library.
