### ISSUE TITLE
queries.hpp should include algorithms outside of namespace

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#22]
`queries.hpp` includes a bunch of other headers, but it does it inside a namespace. This is a problem when you need to add an external header to one of these files. Then, you're including, say, `tbb` namespace inside `ds2i`, which makes it `ds2i::tbb`.

Rather, we should put the namespace in each of those files separately.

**Comment by amallia** [comment]
I agree. Let's do this ASAP.

**Comment by elshize** [comment]
Additionally, each file needs to include all needed headers. Now, we have some weird situation in which the order of includes in an executable might cause errors. This is very bad.

**Comment by elshize** [comment]
This problem apparently isn't limited to the query algorithms. For example, `topk_queue.hpp` exhibits a similar issue of not including `util/util.hpp`, and therefore failing if it's not included before. But of course it shouldn't be needed explicitly in `.cpp` file if I don't use anything from utils there.

Long story short, it's kind of a mess.
