### ISSUE TITLE
Document query format

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#245]
The input query format should be documented in the docs.

**Comment by ansariyusuf** [comment]
I want to convert TREC 2013 queries in to PISA Query format. As told, I tried to use extract_topics to convert TREC queries. But, I am getting the following error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not consume tag: <top>
Aborted (core dumped)

I have tried passing a text file containing TREC 2013 queries (format: <queryid>:query). I also passed TREC 2103 topics (XML file) as an input to ./extract_topics bu I got the same error message. Can you help me with this issue?

**Comment by elshize** [comment]
> a text file containing TREC 2013 queries (format: :query)

Can you show one line from this file?

This type of queries should just go directly to the `queries` or `evaluate_queries` programs. `extract_topics` is designed to be used with this type of files: https://trec.nist.gov/data/terabyte/04/04topics.701-750.txt

Can you attach your XML file (or a snippet)?

**Comment by ansariyusuf** [comment]
Following is the snippet of my text file:
201:raspberry pi
[https://trec.nist.gov/data/web/2013/web2013.topics.txt](url)

Following is the snippet of XML file:
[https://trec.nist.gov/data/web/2013/trec2013-topics.xml](url)
```
<webtrack2013>
<!-- Please note that topic and subtopic types (faceted/ambiguous,
     inf/nav are meant as a general indicator and should not be taken
     as definitive aspects of the query intent. -->

<!-- Note that the first subtopic is always identical to the description
     sentence.  This is to ensure that adhoc-task results are also relevant
     to the subtopic task. -->

<topic number="201" type="faceted">
  <query>raspberry pi</query>
  <description>
    What is a raspberry pi?
  </description>
  <subtopic number="1" type="inf">
    What is a raspberry pi?
  </subtopic>
  <subtopic number="2" type="inf">
    What software does a raspberry pi use?
  </subtopic>
  <subtopic number="3" type="inf">
    What are hardware options for a raspberry pi?
  </subtopic>
  <subtopic number="4" type="nav">
    How much does a basic raspberry pi cost?
  </subtopic>
  <subtopic number="5" type="inf">
    Find info about the raspberry pi foundation.
  </subtopic>
  <subtopic number="6" type="nav">
    Find a picture of a raspberry pi.
  </subtopic>
</topic>
</webtrack2013>
```

I tried passing passing the text file directly to the ./queries program. but, I get a bunch of warnings:
![image](https://user-images.githubusercontent.com/23194673/64537898-56335980-d324-11e9-8deb-5eee204b9f25.png)

**Comment by elshize** [comment]
`parse_collection` program should produce a `*.termlex` file. You need to pass this file to `--terms` argument when calling `queries`.

**Comment by ansariyusuf** [comment]
I did as you asked. Now, the ./queries program is segfaulting:
![image](https://user-images.githubusercontent.com/23194673/64548660-c4cde280-d337-11e9-9229-3012e78eb72b.png)

**Comment by elshize** [comment]
Ok, this doesn't seem to be related to parsing queries anymore. Can you compile it in Debug and post the stack trace from `gdb`?

**Comment by ansariyusuf** [comment]
I compiled with flag "-g" and then ran gdb. From gdb, I ran ./queries and got the following output:
![image](https://user-images.githubusercontent.com/23194673/64552930-0911b080-d341-11e9-9a29-d8a45a6263ec.png)
![image](https://user-images.githubusercontent.com/23194673/64552958-1a5abd00-d341-11e9-8994-10c6b8e9e959.png)
![image](https://user-images.githubusercontent.com/23194673/64552984-2ba3c980-d341-11e9-84b4-c278954fa9e7.png)

**Comment by elshize** [comment]
There are two more tests we can run here that might help us understand what's happening:
1. Run `create_freq_index` again, and make sure that you run it with the same codec --- maybe the file is corrupted or you created a different type of index by accident; that would explain what happened.
2. If (1) doesn't help, then compress the index with another codec, say, `block_simdbp`, and run the query to see if it fails or not. The problem seems to originate from the Elias-Fano-specific code.

If you could do these two things, that would definitely help out with finding the problem.

**Comment by ansariyusuf** [comment]
As requested, I ran create_freq_index again and this time I made the index type as block_optpfor. After, creating the index, I ran the queries program. It segfaulted, I have attached the backtrace from gdb:
![image](https://user-images.githubusercontent.com/23194673/64642203-7a6f6300-d416-11e9-8cfd-89b7086dc7a7.png)

I have repeated the entire process with index type pefopt and when I run ./queries I get a segfault.
Please advice me what I should do to resolve this issue. Thank you!

**Comment by elshize** [comment]
Ok, one more question before I investigate further: are you on `master` right now? And if not, then which commit are you on?

**Comment by ansariyusuf** [comment]
I think I am on master:
![image](https://user-images.githubusercontent.com/23194673/64702907-1602e100-d4b4-11e9-8986-4dee8c0cc2be.png)

**Comment by elshize** [comment]
Can you run `git status`?

**Comment by ansariyusuf** [comment]
Following is the output of git status:
![image](https://user-images.githubusercontent.com/23194673/64704699-5ca60a80-d4b7-11e9-9f5d-0eea229492ff.png)

**Comment by elshize** [comment]
I'm running some tests to see if I can reproduce it. I'll get back to you when I get some results.

**Comment by ansariyusuf** [comment]
If you need the collection that I am trying to parse and run queries on, do let me know. I will share it

**Comment by JMMackenzie** [comment]
@elshize @ansariyusuf Did either if you end up figuring this one out?

**Comment by elshize** [comment]
Nope, I never got to the bottom of this, @ansariyusuf have you ever fixed it, what happened to this? I'm sorry I didn't get back to you, I have been busy and this one just slipped my mind. If the problem still persist, let's tackled it!

**Comment by ansariyusuf** [comment]
I did a fresh installation of PISA on a different machine and followed the steps as told to me by @elshize 
 and it happened to work.

**Comment by elshize** [comment]
In that case, let's close this one, feel free to open it if you experience similar problems in the future.
