### ISSUE TITLE
Krovetz stemmer multi-thread bug with parse_collection

### ISSUE THREAD

**Issue by ansariyusuf** [pisa-engine/pisa#261]
**Describe the bug**
When I use parse collection with krovetz stemmer with more than 2 threads, the program crashes throwing the following error:
`** glibc detected *** ./parse_collection: free(): invalid next size (fast): 0x00007f7eac191cb0 **`

**To Reproduce**
1. use CW12  or CW12 subset as the collection to be parsed
2. pass the unzip stream to the ./parse_collection (running it with more than 2 threads)

**Comment by binshengliu** [comment]
I can reproduce this. I suspect this might be related to KrovetzStemmer::stem being overwritten by multiple threads as there is only one such instance.

I made the following modification as a workaround, but there might be some performance penalty.
```
diff --git a/src/parse_collection.cpp b/src/parse_collection.cpp
index 95b7996..dbb6dab 100644
--- a/src/parse_collection.cpp
+++ b/src/parse_collection.cpp
@@ -158,8 +158,8 @@ std::function<std::string(std::string &&)> term_processor(std::optional<std::str
         };
     }
     if (*type == "krovetz") {
-        static stem::KrovetzStemmer kstemmer;
         return [](std::string &&term) -> std::string {
+            stem::KrovetzStemmer kstemmer;
             boost::algorithm::to_lower(term);
             return kstemmer.kstem_stemmer(term);
         };
```

**Comment by amallia** [comment]
@binshengliu could you create a PR with your fix? Thanks

**Comment by binshengliu** [comment]
This isn't a really usable fix. It would create a stemmer instance for any single term and make the parser terribly slow.

I'd suggest delaying the stemmer instantiation to each thread as KrovetzStemmer class isn't thread-safe. More needs to be done to fix it.
