### ISSUE TITLE
Address sanitizer failures

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#264]
A number of tests fail when run with address sanitizer. Note that some might be due to TBB problems but there are definitely some that are strictly in our code. Needs further investigation.

**Steps To Reproduce**
1. `cmake -DUSE_SANITIZERS=ON -DCMAKE_BUILD_TYPE=Debug ..`
2. `make`
3. `ctest`

**Error message**
```
The following tests FAILED:
	  5 - test_block_codecs:block_codecs (Failed)
	  9 - test_bmw_queries:block_max_wand (Failed)
	 32 - test_forward_index_builder:Merge forward index batches (Failed)
	 34 - test_forward_index_builder:Build forward index (Failed)
	 35 - test_freq_index:freq_index (Failed)
	 46 - test_invert:Invert a range of documents from a collection (Failed)
	 47 - test_invert:Invert collection (Failed)
	 52 - test_partition_fwd_index:copy_sequence (Failed)
	 53 - test_partition_fwd_index:Rearrange sequences (Failed)
	 55 - test_partitioned_sequence:partitioned_sequence (Failed)
	 63 - test_positive_sequence:positive_sequence (Failed)
	 70 - test_ranked_queries:Ranked query test - ranked_or_taat_query_acc<SimpleAccumulator> (Failed)
	 71 - test_ranked_queries:Ranked query test - ranked_or_taat_query_acc<LazyAccumulator<4>> (Failed)
	 72 - test_ranked_queries:Ranked query test - wand_query (Failed)
	 73 - test_ranked_queries:Ranked query test - maxscore_query (Failed)
	 74 - test_ranked_queries:Ranked query test - block_max_wand_query (Failed)
	 75 - test_ranked_queries:Ranked query test - block_max_maxscore_query (Failed)
	 76 - test_ranked_queries:Ranked query test - range_query_128<ranked_or_taat_query_acc<SimpleAccumulator>> (Failed)
	 77 - test_ranked_queries:Ranked query test - range_query_128<ranked_or_taat_query_acc<LazyAccumulator<4>>> (Failed)
	 78 - test_ranked_queries:Ranked query test - range_query_128<wand_query> (Failed)
	 79 - test_ranked_queries:Ranked query test - range_query_128<maxscore_query> (Failed)
	 80 - test_ranked_queries:Ranked query test - range_query_128<block_max_wand_query> (Failed)
	 81 - test_ranked_queries:Ranked query test - range_query_128<block_max_maxscore_query> (Failed)
	 82 - test_ranked_queries:Ranked AND query test - block_max_ranked_and_query (Failed)
	 83 - test_ranked_queries:Top k (Failed)
	 93 - test_wand_data:wand_data_range (Failed)
```

**Environment info**
Operating System: Linux
Compiler name: Clang
Compiler version: 9

**Comment by JMMackenzie** [comment]
I think they are coming from this call (and possibly more):

https://github.com/pisa-engine/pisa/blob/13353328f6746dfb59c0d371d4b2f20be6ff9d95/include/pisa/freq_index.hpp#L34

The reason seems to be related to #265 - TBB does not explicitly destroy some objects unless you scope the manager (so it gets destroyed when it goes out of scope). It may not cover all of them, but I am sure it covers a lot of them, since many of the tests rely on building a sample index.

**Comment by elshize** [comment]
Yes, thanks for pointing this out and linking the issue. I'm pretty sure there are some other problems as well, though. I believe it's mostly legacy low-level code. I think `bitvector` is one of them, there are some division by zero or uninitialized variables going on in certain cases, which the analyzer found.
