### ISSUE TITLE
Parsing collection and queries

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#27]
We need to have term/query/document mappings to release data after ECIR, among other things.

I suggest two programs:

1. Collection parser that takes text collection and produces three things:
  a. `binary_collection` to use for tests
  b. a two-way term/ID mapping
  c. a two-way document/ID mapping
2. Query parser that uses the above to translate terms in queries to IDs.

I got some code in my repo that I can use, so I'll try to incorporate it here.

**Comment by amallia** [comment]
Let's have three options for the stemming phase:
- no-stemming
- Porter2 (https://github.com/pisa-engine/Porter2)
- Krovetz (https://github.com/pisa-engine/KrovetzStemmer)

**Comment by amallia** [comment]
How do we deal with PDF/Word/Postscript files usually present in standard collections like Gov2?

I suspect we should check before sending to Gumbo.

**Comment by elshize** [comment]
I wasn't aware there were these files there, so I didn't do anything. If there are some in Clueweb, then that might be why it gets stuck.

**Comment by amallia** [comment]
Closing this issue since https://github.com/pisa-engine/pisa/pull/37 has been merged
