### ISSUE TITLE
Unsigned integer ‘last_doc’ works using an overflow ('block_posting_list' struct)

### ISSUE THREAD

**Issue by gustingonzalez** [pisa-engine/pisa#277]
In the following line:
https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L28
`last_doc` is `uint32_t` and maybe it should be `int32_t`. Although it does not represents a runtime error, conceptually it can be weird: for example, when debugging, its value is shown as 4294967295.

**Comment by amallia** [comment]
I think it is fine to have a document ID which is the greatest possible. Remember we do not want to have last_doc equal to `-1` actually, but it is just a way of setting it to `UINT32_MAX`

@elshize comments?

**Comment by gustingonzalez** [comment]
In following line, it makes sense that its value be -1:
https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L37

Then, on first iteration, this -1 allows to preserve the value of the first gap:
```
docs_buf[0] = doc - (last_doc) - 1  
docs_buf[0] = doc - (-1) - 1
docs_buf[0] = doc
```

**Comment by elshize** [comment]
There's definitely something shady going on here:
https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L37

So if `last_doc` is the largest integer (which btw you get by using `std::numeric_limit<T>::max()` if anything), then here `doc - last_doc - 1` we subtract an `uint32_t` by the maximum possible `uint32_t`, so we get an overflow right off the bat. I guess the idea is that you do `doc - (last_doc + 1)`. This is technically correct but also very meh.

Looking at the code, I think we can get rid of the variable altogether, and express anything in terms of  `block_base`:

```cpp
            uint32_t block_base = 0;
            for (size_t b = 0; b < blocks; ++b) {
                uint32_t cur_block_size =
                    ((b + 1) * block_size <= n)
                    ? block_size : (n % block_size);

                auto old_base = block_base;
                for (size_t i = 0; i < cur_block_size; ++i) {
                    uint32_t doc(*docs_it++);
                    docs_buf[i] = doc - block_base;
                    block_base = doc + 1;

                    freqs_buf[i] = *freqs_it++ - 1;
                }
                *((uint32_t*)&out[begin_block_maxs + 4 * b]) = block_base - 1;

                BlockCodec::encode(docs_buf.data(), block_base - old_base + 1 - (cur_block_size - 1),
                                   cur_block_size, out);
                BlockCodec::encode(freqs_buf.data(), uint32_t(-1), cur_block_size, out);
                if (b != blocks - 1) {
                    *((uint32_t*)&out[begin_block_endpoints + 4 * b]) = out.size() - begin_blocks;
                }
            }
```

Can you guys check if the math's good?

**Comment by amallia** [comment]
> In following line, it makes sense that its value be -1:
> https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L37
> 
> Then, on first iteration, this -1 allows to preserve the value of the first gap:
> 
> ```
> docs_buf[0] = doc - (last_doc) - 1  
> docs_buf[0] = doc - (-1) - 1
> docs_buf[0] = doc
> ```

Good point, but when dealing with unsigned integers, if you subtract a max value or you subtract `-1` the effect is the same. Remember that overflow is a defined operation for unsigned integers.

**Comment by elshize** [comment]
@amallia can you check my code above? What do you think?

**Comment by gustingonzalez** [comment]
> > In following line, it makes sense that its value be -1:
> > https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L37
> > 
> > Then, on first iteration, this -1 allows to preserve the value of the first gap:
> > ```
> > docs_buf[0] = doc - (last_doc) - 1  
> > docs_buf[0] = doc - (-1) - 1
> > docs_buf[0] = doc
> > ```
> 
> Good point, but when dealing with unsigned integers, if you subtract a max value or you subtract `-1` the effect is the same. Remember that overflow is a defined operation for unsigned integers.

Thanks @amallia. It's clear that both operations are the same. Even so, the unsigned overflow may seem strange (personally, when I was debugging, I had to think a little about what was happening there). That is, it sounds more natural to subtract directly -1.

In the other hand, regarding the piece of code proposed by @elshize, I think improves the readability of the delta encoding process. In addition, perhaps the `encode` call could be further improved by storing the second parameter on a separated variable, for example:
```cpp
// auto doc_gaps_universe = block_base - old_base + 1 - (cur_block_size - 1)
auto doc_gaps_universe = (block_base - old_base) - cur_block_size;
BlockCodec::encode(docs_buf.data(), doc_gaps_universe, cur_block_size, out);
```
Anyway, I'm not so sure (yet) if the proposed variable name represents what it really does.

By the way, is there any reason to call the base used for the delta encoding as `block_base`? Maybe something as `doc_base` or `delta_base` could be much clearer.

**Comment by amallia** [comment]
> There's definitely something shady going on here:
> https://github.com/pisa-engine/pisa/blob/d7599b1a909e6fdde7ca59611426c956493a5268/include/pisa/block_posting_list.hpp#L37
> 
> So if `last_doc` is the largest integer (which btw you get by using `std::numeric_limit<T>::max()` if anything), then here `doc - last_doc - 1` we subtract an `uint32_t` by the maximum possible `uint32_t`, so we get an overflow right off the bat. I guess the idea is that you do `doc - (last_doc + 1)`. This is technically correct but also very meh.
> 
> Looking at the code, I think we can get rid of the variable altogether, and express anything in terms of `block_base`:
> 
> ```c++
>             uint32_t block_base = 0;
>             for (size_t b = 0; b < blocks; ++b) {
>                 uint32_t cur_block_size =
>                     ((b + 1) * block_size <= n)
>                     ? block_size : (n % block_size);
> 
>                 auto old_base = block_base;
>                 for (size_t i = 0; i < cur_block_size; ++i) {
>                     uint32_t doc(*docs_it++);
>                     docs_buf[i] = doc - block_base;
>                     block_base = doc + 1;
> 
>                     freqs_buf[i] = *freqs_it++ - 1;
>                 }
>                 *((uint32_t*)&out[begin_block_maxs + 4 * b]) = block_base - 1;
> 
>                 BlockCodec::encode(docs_buf.data(), block_base - old_base + 1 - (cur_block_size - 1),
>                                    cur_block_size, out);
>                 BlockCodec::encode(freqs_buf.data(), uint32_t(-1), cur_block_size, out);
>                 if (b != blocks - 1) {
>                     *((uint32_t*)&out[begin_block_endpoints + 4 * b]) = out.size() - begin_blocks;
>                 }
>             }
> ```
> 
> Can you guys check if the math's good?

I think `block_base = doc + 1;` can generate some confusion.

I think the correct one should be:
`                BlockCodec::encode(docs_buf.data(), block_base - 1 - old_base - (cur_block_size - 1),
                                   cur_block_size, out);`

**Comment by elshize** [comment]
> I think block_base = doc + 1; can generate some confusion.

Can you elaborate? Not sure what you're referring to.

At the same time, I want to propose to replace this
```cpp
BlockCodec::encode(freqs_buf.data(), uint32_t(-1), cur_block_size, out);
```
with
```cpp
BlockCodec::encode(freqs_buf.data(), std::numeric_limits<uint32_t>::max(), cur_block_size, out);
```
