### ISSUE TITLE
BMW skip logic

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#298]
https://github.com/pisa-engine/pisa/blob/8d55d2f0be32632c1558a9118010828a2157de00/include/pisa/query/algorithm/block_max_wand_query.hpp#L125-L132

I think `q_weight` should probably be `max_weight` as we want to move the cursor behind the pivot with the largest upper-bound score. I think `q_weight` is almost always = 1.

Thoughts?

**Comment by elshize** [comment]
Yes, we were literally having this discussion. Apparently, it doesn't really have impact on performance, at least not that we noticed. Maybe it should be further investigated. One thing for sure, picking the largest `q_weight` is simply a waste of time. Is it at all possible that removing this loop altogether will give us some speed-up? We should probably measure both that and by max score.

**Comment by JMMackenzie** [comment]
Right, so it would be good to compare doing either:

1) Find and then move the list with the highest max_score
2) Just move the pivot list

Any other candidates?

**Comment by amallia** [comment]
Yes, for me we can give a try to (1) immediately as it directly correlates to IDF, which is the choice of the original paper. 
Another option is to move based on the list length.

**Comment by elshize** [comment]
Yeah, we should just change to `max_weight` now. As @amallia says, it's following the original paper, and it's what it was before. Any other experimentation we can leave for later.
