### ISSUE TITLE
Incorrect size for binary sequence in Invert

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#306]
The beginning of the `.docs` canonical expects a single sequence, `1 N` where `N` represents the number of documents in the index. However, the code seems to take the number of terms instead.

https://github.com/pisa-engine/pisa/blob/5a7f149fb6a54e168ce70c51179e967c2e3bbe6a/include/pisa/invert.hpp#L176

We should double check that this is a bug, and then replace this with the correct size. I think we can use something like:
```
std::uint32_t count = index.document_sizes.size();
```

**Comment by elshize** [comment]
It seems to be a bug. @amallia didn't we talk about something similar where you thought you had found a bug? Wasn't it somehow related? Do we even use this value? I can try to investigate but currently pretty busy.

**Comment by amallia** [comment]
I opened a PR
