### ISSUE TITLE
Quantization segmentation faults

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#328]
Since we now support quantization I wanted to mess around with it and came across this bug.

When building a quantized index via `create_freq_index` I get a segmentation fault.

The problem is that we instantiate a `scorer` without the scorer having `m_wdata` -- we then try to do `auto term_weight = query_term_weight(term_len, this->m_wdata.num_docs());` when we call `term_scorer` which leads to the segmentation fault.

I'm not sure what the best approach is to fix this - perhaps we can compute the normalized term lengths and the number of documents *first* and add those into the `wand_data` when we initialize it? Then, the scorer would have the necessary information to begin quantization.

I have also added some minor fixes to the quantization code in the branch `quant-fixes` so we can develop on that for this fix.

**Comment by JMMackenzie** [comment]
Following up, it seems that the process is to first build the `wand_data` and then pass it into the `create_frequency_index` binary. If this is what is intended, it may be worth adding guards to the CLI to ensure that if `--quantize` is set, then `--wand` is also provided.

**Comment by amallia** [comment]
Agreed. We should ensure to have a wand file if `--quantize` is passed
