### ISSUE TITLE
Fix selective_queries.cpp

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#336]
**Describe the bug**
1. `selective_queries.cpp` should be moved into `tools`
2. The task is not performing any selective selection 
```cpp
        uint64_t and_results = and_query<false>()(index, query);
        uint64_t or_results = or_query<false>()(index, query);

        double selectiveness = double(and_results) / double(or_results);
        if (selectiveness < 0.005) {

```

**Comment by elshize** [comment]
What is it supposed to do anyway?

**Comment by amallia** [comment]
Selective is defined as
> any query such that the fraction of the documents that contain all its terms over those that contain at least one of them is small (we set this threshold to 0.5%).
