### ISSUE TITLE
Pisa as c++ library

### ISSUE THREAD

**Issue by scisci** [pisa-engine/pisa#355]
Is it possible to build this as a statically linked library instead of a CLI? I am interested in adding full text search to an application I am writing. The examples I see in the docs all appear to use a CLI so wondering if the developers can clarify if it should be possible. Ideally I'd like to use CMake to add it to my project so any examples from someone who has done this before would be helpful.

**Comment by elshize** [comment]
Yes, it is possible. You can take a look here for an example: https://github.com/tantivy-search/search-benchmark-game/tree/master/engines/pisa-0.8.2 Also feel free to let us know if something's not working.

This part is important: https://github.com/tantivy-search/search-benchmark-game/blob/3f19eda411c64d08940901bf5ade74e9ab4ef23e/engines/pisa-0.8.2/CMakeLists.txt#L35 You can turn these options off to avoid building CLI or tests.

**Comment by scisci** [comment]
Perfect. Thanks for the quick reply.
