### ISSUE TITLE
Compiler crash on Apple LLVM version 10.0.1

### ISSUE THREAD

**Issue by jsmer005** [pisa-engine/pisa#369]
```
[ 71%] Building CXX object tools/CMakeFiles/parse_collection.dir/parse_collection.cpp.o
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/4j/xz5pv34j0sz20jn_29rn6hmh0000gn/T/parse_collection-c61b1e.cpp
clang: note: diagnostic msg: /var/folders/4j/xz5pv34j0sz20jn_29rn6hmh0000gn/T/parse_collection-c61b1e.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/black/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

********************
make[2]: *** [tools/CMakeFiles/parse_collection.dir/parse_collection.cpp.o] Error 254
make[1]: *** [tools/CMakeFiles/parse_collection.dir/all] Error 2
make: *** [all] Error 2
```
I've spent hours trying to figure out what is going on here, but to no end. Can someone tell me why Clang continually crashes on this particular source file?

**Comment by elshize** [comment]
No idea but it looks like a compiler bug. Here's a few questions:
- Did you look at those diagnostic messages?
- What version/commit of PISA are you trying to compile?
- Are you able to try compiling with regular clang or gcc?

@amallia do you have any idea? Have you experienced anything like this on your mac?

**Comment by jsmer005** [comment]
Hi, thanks for looking into this.
1) I looked for the crash backtrace, but couldn't find it anywhere. It wasn't in the folder listed or anywhere else in the console.
2) I am compiling a version of PISA that I cloned this morning. I believe it is v0.8.2.
3) I have not tried using only clang/gcc. Would you tell me how I might go about that?

Thank you!

**Comment by elshize** [comment]
I can only guess you you have some kind of package manager and there's a clang or gcc package. I mean you can always compile it but I'm almost positive there's a better way. Sorry, I don't really know how things work on mac, I don't wanna steer you wrong. @amallia is our resident mac user, so hopefully he'll chime in when he sees it.

I checked that it compiles on travis with AppleClang 11, so upgrading could maybe help.

**Comment by amallia** [comment]
@jsmer005 I am using Clang 9 on my MacOS setup, but not the Apple Clang.
I see you are running Apple Clang 10. AFAIK Apple Clang 10 is not fully compatible with C++17.

Our Travis instance is running fine on Xcode 11.2.1 which is Apple clang version 11.0.0, as @elshize already mentioned. I can try to add Clang 10 and see if we have the same issue.

My recommendation is to install apple Clang 9 and make it your default. With `brew` you do `brew install llvm` and you get LLVM installed.
Then if you want to use LLVM Clang as a default compiler you can add the following to your `.base_profile` file
```
# LLVM
export PATH=/usr/local/opt/llvm/bin:$PATH
export CC=clang
export CXX=clang++
export C_INCLUDE_PATH=$(llvm-config --includedir):$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$(llvm-config --includedir):$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$(llvm-config --libdir):$LIBRARY_PATH
```

Or you can upgrade to Apple Clang 11 and you will be sure that it will work.

**Comment by amallia** [comment]
Testing: https://github.com/pisa-engine/pisa/pull/371

**Comment by elshize** [comment]
@jsmer005 so it turns out, at least on Travis, PISA compiles just fine with 10.3, so even upgrading to this one should work, hopefully.

I'm guessing what you're experiencing is just a compiler bug that has been fixed in later point versions.

If you decide to upgrade, let us know if it helps.

**Comment by jsmer005** [comment]
O.K., thank you for all your help! I'll try upgrading to a newer version of LLVM. It looks like this is obviously just a problem on my end, so I'm closing the issue.

**Comment by amallia** [comment]
No problem, feel free to reopen if you need more help. And let us know how it goes!

P.S. don’t forget to join our slack channel 😬

**Comment by jsmer005** [comment]
Updating X-Code to 11.4.1 (w/ Clang v. 11.0.3) solved the problem. Thanks.
