### ISSUE TITLE
Speed up CI for PRs

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#372]
I propose to limit Travis build for PRs to few essential checks.
First, we can compile headers since it is quite fast so we make sure all the included are in place.
Then we can run Clang-format check since it is also quite fast.
Finally instead of checking multiple compiler versions we could run the latest (or oldest) version of the compiler only.

When we merge into master Travis will run a deeper check and test for all the supported compilers. Opinions?

**Comment by elshize** [comment]
I agree. I'd like to keep clang-tidy build for each PR though. If we have to choose which compilers to run primarily, we should use the latest version.

Before we set up to build more on `master` but not other, we can probably more easily reduce the time by not running tests on all builds, just checking if it compiles.

Do you want to try building that CI pipeline with Github actions? It might be a good time to try that while we're making changes, simply leave travis as is (maybe remove those tests I mentioned above) and set up a separate pipeline on github.

**Comment by JMMackenzie** [comment]
Sure, I am also in favor of this. I also agree with @elshize - it's probably a good chance to try the GitHub actions approach instead of Travis.

**Comment by gustingonzalez** [comment]
Hello everyone. Maybe the older and the latest version of `gcc` and `clang` could be checked. On the other hand, consider to update the [documentation](https://pisa.readthedocs.io/en/latest/getting_started.html) based on the changes.

**Comment by elshize** [comment]
I'm closing this in favor of #521
