### ISSUE TITLE
WAND data should be required?

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#381]
Right now, the CLI doesn't require `--wand` for `compute_intersection` but it fails if I don't pass it. But more generally, is any querying have any chance of working without wand data? Does it make sense for it to be optional?

Edit: in fact, if you look at `evaluate_queries`, all algorithms require wand data, so no reason not to require it at CLI. As far as I can tell, only the not ranked algorithms don't require it (in `tools/queries.cpp`). We should definitely require it for any command that won't work otherwise.

**Comment by JMMackenzie** [comment]
I guess we could duplicate:

https://github.com/pisa-engine/pisa/blob/a84fada8bbdad250ac65d7a2809a444943e16c97/tools/app.hpp#L36

And have `OptionalWandData` and `RequiredWandData` or something?

We could also just template it but I am not sure how elegant it would be passing a `std::optional` after making it required at CLI?

**Comment by elshize** [comment]
We could actually template it and have the return value to be different based on the template (`...` is whatever compile-time check we need to make):
```cpp
[[nodiscard]] auto wand_data_path() const /* no type specified */
{
    if constexpr (...) {
        return m_wand_data_path;
    } else {
        return *m_wand_data_path;
    }
}
```

Alternatively, you can have a simple function, but use `std::conditional` to define the type of the member variable:
```cpp
using value_type = std::conditional_t<..., std::string, std::optional<std::string>>;
[[nodiscard]] auto wand_data_path() const -> value_type
{
    return m_wand_data_path;
}
value_type m_wand_data_path;
```
