### ISSUE TITLE
reorder-docids --bp -p does not print the new ordering

### ISSUE THREAD

**Issue by ybarsami** [pisa-engine/pisa#385]
Before the merging of recursive_graph_bisection into reorder-docids (pull 363 : https://github.com/pisa-engine/pisa/pull/363), I was able to use -p to print the new ordering when doing a recursive graph bisection.

Now, instead of calling recursive_graph_bisection, we have to call reorder-docids --bp (or the equivalent reorder-docids --recursive-graph-bisection). But this time, the executable does not seem to take the -p into consideration, even though, according to reorder-docids --help, it should still do so.

**Comment by elshize** [comment]
Thanks for reporting this. There is a bug right here: https://github.com/pisa-engine/pisa/blob/a84fada8bbdad250ac65d7a2809a444943e16c97/tools/reorder_docids.hpp#L23 Looking at the code, you should be able to print it by **not including** `-p` (the logic is reversed) until I get a chance to fix it. (You're also welcome to submit a PR removing the `not` from that line if you get to it before I do---rather busy at the moment)

**Comment by JMMackenzie** [comment]
Closed via #386
