### ISSUE TITLE
Support modern WARC/1.0 inputs in parse_collection

### ISSUE THREAD

**Issue by mpetri** [pisa-engine/pisa#397]
**Describe the bug**
Downloading a WARC file from the common crawl and piping it into `parse_collection` results in an empty forward index.

**To Reproduce**
1. `wget https://commoncrawl.s3.amazonaws.com/crawl-data/CC-NEWS/2018/02/CC-NEWS-20180201022700-00187.warc.gz`
2. `zcat ./CC-NEWS-20180201022700-00187.warc.gz | ./parse_collection -o ./forward -j 5 -f warc --stemmer porter2 --content-parser html`
3. Check file size of the forward index

**Error message**
```
-rw-rw-r-- 1 ubuntu ubuntu    8 Jun  1 01:51 forward
-rw-rw-r-- 1 ubuntu ubuntu   16 Jun  1 01:51 forward.doclex
-rw-rw-r-- 1 ubuntu ubuntu    0 Jun  1 01:51 forward.documents
-rw-rw-r-- 1 ubuntu ubuntu   16 Jun  1 01:51 forward.termlex
-rw-rw-r-- 1 ubuntu ubuntu    0 Jun  1 01:51 forward.terms
-rw-rw-r-- 1 ubuntu ubuntu    0 Jun  1 01:51 forward.urls
```

**Expected behavior**
The warc records should have been extracted/parsed/added to the forward index.

**Comment by JMMackenzie** [comment]
@elshize this is probably one for you - could it be something to do with WARC compliance?

**Comment by JMMackenzie** [comment]
I suspect the issue is here - seems that it requires a TREC identifier which is non-standard WARC. Perhaps we can refactor such that it can proceed but assigns some other identifier?

https://github.com/pisa-engine/warcpp/blob/master/include/warcpp/warcpp.hpp#L119

After manually editing the CC-News file to add a single `WARC-Trec-ID: ABC-123` I see the following:

```
8.0K	forward
4.0K	forward.doclex
4.0K	forward.documents
8.0K	forward.termlex
4.0K	forward.terms
4.0K	forward.urls
```

``` 
head forward.documents
ABC-123
```

```
head forward.terms 
1
10pm
14
15
16
```

**Comment by mpetri** [comment]
WARC has a required header called `WARC-Record-ID` which could be used instead if the TREC-ID is not available. From the spec:


> A WARC-Record-ID is an identifier assigned to the current record that is globally unique for its period of intended use. No identifier scheme is mandated by this specification, but each WARC-Record-ID shall be a legal URI and clearly indicate a documented and registered scheme to which it conforms (e.g. via a URI scheme prefix such as “http:” or “urn:”). Care should be taken to ensure that this value is written with no internal white space.

**Comment by amallia** [comment]
Thank you all! This is a known bug we never solved because we never had to parse CC-NEWS before. Maybe now is the right time to fix it.
TREC WARC differs from standard WARC and we need to switch from one to the other dynamically. I will take a look.
