### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by mpetri** [pisa-engine/pisa#399]
**Describe the bug**
The docs at https://pisa.readthedocs.io/en/latest/compress_index.html#usage talk about using `create_freq_index` which is what the binary was called in `ds2i`. It looks like it was renamed to `compress_inverted_index` and additional features were added?

**To Reproduce**
1. Go to the docs
2. Find the old description

**Expected behavior**
The docs should provide a step-by-step guide to create an index. The `create_wand_data` step seems to be also missing? Is that still necessary?

**Comment by JMMackenzie** [comment]
This is evidently a major issue with PISA currently. It's difficult for newbies to get going with it. 

I think what would be super useful is to follow the Anserini "Reproducibility" path of providing end-to-end markdown files showing the process. See, for example: https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md

**Comment by elshize** [comment]
We've upgraded the docs since this was opened, here's one link of interest: https://pisa.readthedocs.io/en/latest/experiments/regression-robust04.html
