### ISSUE TITLE
Heap condition slows down queries on quantized index

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#415]
Because `would_enter` method of the top-k heap checks if the score is **greater or equal**, it means that sometimes a document will be entered into the heap just to be removed. This rarely happens when scores are decimals, but it's much more frequent when the scores are quantized. It especially affects VBMW algorithm, and can slow it down in some cases such that a query on the quantized index is several times slower than one on the non-quantized index.

**Comment by JMMackenzie** [comment]
Agreed, this logic should only accept documents that exceed the threshold. This means the first `k` documents that have the tied score would enter and the rest would not.

**Comment by JMMackenzie** [comment]
@elshize are we comfortable just modifying the heap logic such that:

`bool would_enter(float score) const { return score > m_threshold; }` 

In lieu of: https://github.com/pisa-engine/pisa/blob/master/include/pisa/topk_queue.hpp#L47

**Comment by elshize** [comment]
Yes, imo that's the correct logic here.

But when talking about the correctness of the entire library, it's not as easy. I thought about it, and it seems that we use two different definitions of _threshold_ throughout the code.
1. Threshold as a score that has to be exceeded to enter the queue.
2. Threshold as the score of the k-th document.

Note that (1) is not just a matter of `would_enter` condition. Even if it's `>=`, then it doesn't actually change the semantics for when the queue is full. The document will still not enter the queue, it will just not enter it less efficiently. However, it's a different semantic when the queue is not full, and we have a non-zero threshold. In other words, we have inconsistent semantic, which means `>=` is a straight up bug.

Then we have (2) whenever we calculate the threshold, either estimating or just calculating the actual threshold. The latter is the best example of (1) and (2) not being the same.

Note that trying to work around it by changing the value of the threshold at the beginning of query processing is (a) confusing, and (b) incorrect, really. Since we accept thresholds from the command line, they could come from anywhere, and we don't know if it's the definition (1) or (2).

I strongly believe we need to pick one definition of "threshold" and stick with it. It also needs to be clearly documented.

I am not entirely sure if we can use (2) and not degrade performance, but I didn't think too hard about it.

If we go the (1) route, we need to fix how we calculate thresholds. Theoretically speaking, we should calculate/estimate the first lower score than the k-th document's. But in practice, we can calculate threshold as we have been doing so far, as the k-th score, and then post-process it:
```cpp
threshold = ...;
if (quantized) {
    threshold = std::max(threshold - 1.0, min_possible_score);
} else {
    threshold = std::max(std::nextafter(threshold, std::numeric_limits<float>::lowest()), min_possible_score);
}
```
Note that I decrease the floats towards the lowest value to support also non-positive scores and `min_possible_score` would be 0 for non-negative scorers like BM25. Which makes me think about another potential issue: I'm looking at the `qld` scorer, and we use log there. Isn't QL score a probability? Wouldn't all our log-scores be negative? Yet we choose max of score and 0. Am I missing something there?

**Comment by JMMackenzie** [comment]
I agree with your proposal and the general precision required in getting these checks and bounds "correct" -- I think (1) is what we want to use, agreed.

As for QL: The document length normalization component is negative, but the other part is positive. I believe we use a model like Lucene: https://lucene.apache.org/core/4_7_1/core/org/apache/lucene/search/similarities/LMDirichletSimilarity.html

Pretty sure the scores are thus guaranteed positive (because of that max(0, ) call).

**Comment by elshize** [comment]
Got it. So it seems like all our scorers are positive. In fact, it seems like in the current state they have to because of how we sum up scores (negative scores would require scoring all terms for each document, including those with frequency 0). So we can just implement it as:
```cpp
threshold = ...;
threshold = std::max(
    quantized ? threshold - 1.0 : std::nextafter(threshold, 0.0),
    0.0
);
```

**Comment by JMMackenzie** [comment]
Yes, I agree with this solution. So we reduce thresholds by an epsilon, and we modify to `>` instead of `>=` for the `would_enter` call. Is that all that's required?

**Comment by elshize** [comment]
> Yes, I agree with this solution. So we reduce thresholds by an epsilon, and we modify to > instead of >= for the would_enter call. Is that all that's required?

I believe so. It should be verified, though, once implemented. By that, I mean we should verify the performance, but also we should have some kind of integration test to see if our generated thresholds work well with query processing.

**Comment by JMMackenzie** [comment]
Just taking a look again now. Do we want to include the "minus epsilon" component during threshold creation (with the tool) or when we read thresholds into the querying programs?

**Comment by amallia** [comment]
I would say when we read the thresholds into the querying programs...

**Comment by elshize** [comment]
If we have the condition as `>`, then I think it should be when we compute the thresholds. The reason is to have only one definition of threshold and stick to it. It's important that the threshold-computing tools produce thresholds, and not something close to what thresholds are that need to be magically fixed. I'd like to avoid a situation in which a threshold is something in CLI for `queries` but something else inside `topk_queue` because it will lead to confusion. See also my comment in this issue from June 25.
