### ISSUE TITLE
BP misteriously failing with multiple threads (rarely)

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#422]
I have found a case in which `reorder-docids --bp` fails when run with more than 1 thread. I haven't been able to figure it out, and I don't have the time to do it right now, so I attach the input data on which it fails (it's one Clueweb09B shard) to be able to reproduce it later.

I tried running with sanitizers and debugging with `gdb` but if I set it to catch any exception, `gdb` itself crashes, and so I wasn't able to figure out what the problem is or where it even occurs.

Here's the command I used:

```bash
reorder-docids --bp \
    -c cw09b-url.inv.013 \
    -o cw09b-url.inv.bp.013 \
    --documents cw09b-url.fwd.013.doclex \
    --reordered-documents cw09b-url.fwd.bp.013.doclex
```

https://drive.google.com/file/d/1ixA98esDKYjHTZkNCLUPx6FVMlV_i9eB/view?usp=sharing

**Comment by JMMackenzie** [comment]
I had a quick look on a Ubuntu box with about 512GiB of RAM, ran with 32 threads.

I noticed the memory usage peaked at around 30% (>  150 GiB) but the program ran successfully. 

1. Are you sure you have sufficient memory to process this shard? It has a relatively large vocab. What if you tried `-m 256` or `-m 1024` or something like that? You could also limit the thread count to reduce memory consumption (unless we've messed something up and things aren't being free'd).
2. On the same line of thought, is the vocabulary of this shard notably larger than the others you tested?

**Comment by elshize** [comment]
Thanks for checking, I'll check (1) and (2) soon.

**Comment by elshize** [comment]
Ok, so I was able to verify that in fact that shard happens to have significantly more terms in it, about 8x the number of the previous shard for example, and uses about as much more memory, too. So I was definitely running out of memory. It's still weird to me that I didn't just get a bad alloc instead of blowing up, but no matter.

BTW, setting `-m 1024` didn't significantly change my memory consumption for that particular shard.

Thanks @JMMackenzie for investigating, since this isn't in fact a bug, I'm closing the issue.
