### ISSUE TITLE
Library Builds

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#459]
As discussed on PyPISA, we need to alter some compilation details for correctly linking. See: https://github.com/pisa-engine/pypisa/issues/1

However, we need to decide whether we'll include these all the time, or whether we want to have two different compilation processes (one for lib builds, for use in PyPISA for example, and one for binaries?)

Any thoughts on this? We might need to double check that we're not introducing any performance regressions when we include these flags, as I know that -fPIC can disrupt inlining for example.

**Comment by elshize** [comment]
I think we could just use it all the time, but to be on the safe side, we can add an option that defaults to whatever we have now and adds the flag if present. If we at some point decide that fPIC is fine by default, we can remove the option.

**Comment by JMMackenzie** [comment]
I've just added a sample PR but feel free to go and edit it -- this is what I imagine we'd want, but perhaps there's a cleaner way?
