### ISSUE TITLE
Replace boost::filesystem (or not)

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#52]
So I'm using `boost::filesystem` right now for convenience, but we wanted to get rid of Boost. It seems that `std::filesystem` compiler support is still very much spotty. We could use `std::experimental::filesystem`, which as far as I know is supported in both gcc and clang, and I think visual studio as well. Not sure about those, though.

Another option is to find an external library but I'm not sure that's a good path to take.

I suggest we stay with `boost::filesystem` right now (we have other Boost dependencies anyway), and once we're closer to getting rid of Boost, we should probably migrate to `std::experimental::filesystem` for wider support (I'm guessing MS will be late to move it to `std::filesystem`).

**Comment by amallia** [comment]
I agree with you. No need to replace `boost::filesystem` until there is other boost stuff to get rid of.
`boost::filesystem` is also used in tests afaik.

**Comment by amallia** [comment]
Since we decide keep boost for now, I think we can close this one for now.
