### ISSUE TITLE
Support pipeline of operations

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#63]
https://github.com/pisa-engine/pisa/blob/e3a31217185e49c7e06c1ce59e5565f16367faf7/src/parse_collection.cpp#L48-L69

I would be nice if we could build a pipeline of actions to perform on the input stream.

We could decide to: parse_warc | strip_http_header | parse_html | stem | ...
It will give us much more freedom and will simplify the code. The pipeline will be first build according to what we are performing (parse_warc or parse_plaintext) and then passed to the forward index builder.

The only library to do so that I am aware of is https://github.com/ericniebler/range-v3

**Comment by elshize** [comment]
Yep, that's a nice library, we should take advantage of it. With caution, though, it's easy to implement something inefficient when you don't pay attention.
