### ISSUE TITLE
Dead code block

### ISSUE THREAD

**Issue by JMMackenzie** [pisa-engine/pisa#65]
Isn't this a dead block? The UB scores are computed in the constructor of the partition and returned as t unless I am mistaken.

https://github.com/pisa-engine/pisa/blob/3672c4c4ded444464cfdaf724010cceda828dfe7/include/pisa/wand_data_compressed.hpp#L119-L126

**Comment by amallia** [comment]
It looks like `doc_score_top` and `max_score` are never used. We should just remove it. 
Thanks

**Comment by amallia** [comment]
https://github.com/pisa-engine/pisa/pull/66
