### ISSUE TITLE
Caching dependencies in Travis

### ISSUE THREAD

**Issue by elshize** [pisa-engine/pisa#67]
Since we have a few dependencies we build every time, can we still cache them even if we use them as subdirectories?

Or, here's an unpopular opinion, maybe we shouldn't build them from subdirectories.

**Comment by amallia** [comment]
I vote for caching :)

**Comment by elshize** [comment]
Do you know how to do it? Since we build within the git tree?

**Comment by amallia** [comment]
> Do you know how to do it? Since we build within the git tree?

I remember that I saw how to do it at some point. I have to check again, because i forgot :(

**Comment by amallia** [comment]
Done in https://github.com/pisa-engine/pisa/pull/95
